POST /v1/auth/login HTTP/1.1
Host: localhost:2000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDg3MDQ5NzMsImV4cCI6MTcwODcwNTg3MywiYXVkIjoiOTQyNjk0ZDgtOWI3NS00MTNmLWEzYjUtNDNlZWU3OTkwMTkwIiwiaXNzIjoidW5pY29ubmVjdC5jb20ifQ.dV7UdoMrJFJXUOEMa3bCvASDw-Y9OcwtDBOskg5nmuo
Content-Type: application/json
Content-Length: 69

{
   "email": "airamtafir@gmail.com",
   "password": "Rifat3566"
}
###
POST /v1beta/models/gemini-pro:generateContent?key=AIzaSyDC6Shnv-m82C5j8yvIQ8-eATKjEfMQy48 HTTP/1.1
Host: generativelanguage.googleapis.com
User-Agent: curl/8.2.1
Accept: */*
Content-Type: application/json
Content-Length: 74

{"contents":[{"parts":[{"text":"Write a story about a magic backpack"}]}]}
###
GET /v1/question/answer/get/1 HTTP/1.1
Host: localhost:2000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDg4NzgxMTgsImV4cCI6MTcwODg3OTAxOCwiYXVkIjoiOThkZTY1ODAtZTUxMi00NzBmLWJhNGUtMzkwMTQ1MzM1MTkyIiwiaXNzIjoidW5pY29ubmVjdC5jb20ifQ.qGTQk1CqcnxGWfGwmsr3T-Iirm08q-2Vp2nwEDxGuxc